### ISSUE TITLE
Link validation

### ISSUE THREAD

**Issue by rowanc1** [curvenote/editor#136]
Currently our URLs are too restrictive. This should likely stop with a regexp approach and use a `new URL()` and look at the throw instead.

For example, doesn't like local hosts with ports, or curve.space. :(

![image](https://user-images.githubusercontent.com/913249/169009971-c8ef102a-7a2b-4aaf-99a3-4564897d04f5.png)

* there is different validation behaviour between the CMD+k initial entry and the validation in the popover

discussion & requirements: https://curvenote.com/@curvenote/architecture/links-in-editor

**Comment by stevejpurves** [comment]
possibly related: https://github.com/curvenote/editor/issues/139

**Comment by rowanc1** [comment]
Fixed in #142.
