### ISSUE TITLE
Overview article structure in left bar

### ISSUE THREAD

**Issue by sarahgarre** [curvenote/editor#140]
It would be great to see the titles up till level 3 (h1,h2,h3) in the overview bar on the left in the editor to keep an easy overview of an articles structure.

**Comment by stevejpurves** [comment]
@sarahgarre work is in progress on this, this week!

**Comment by stevejpurves** [comment]
@sarahgarre this is now deployed in curvenote! thanks for the feedback!

![image](https://user-images.githubusercontent.com/1473646/173796110-bf20ba86-3825-4a8a-8979-a1c0c02a4e4c.png)
