### ISSUE TITLE
Pasting links link the entire content

### ISSUE THREAD

**Issue by rowanc1** [curvenote/editor#148]
I thought we fixed this in the last bit of link changes, but it still does not work. The regexp for matching links must start with the `\^https?...`, and not be as permissive as the inline linker.

**Comment by stevejpurves** [comment]
@rowanc1 @Yxwww I think this is related:

![mqOi7DJIKM](https://user-images.githubusercontent.com/1473646/178363052-2193c6b9-7f63-408b-a982-a51f83b9e069.gif)

Pasting any text with a colon converts to a link.

**Comment by rowanc1** [comment]
This has been fixed!
