### ISSUE TITLE
Demo link in readme file does not work.

### ISSUE THREAD

**Issue by ArmelZy** [curvenote/editor#177]
The demo link points to [https://github.com/curvenote/editor/blob/main/demo/index.tsx](https://github.com/curvenote/editor/blob/main/demo/index.tsx) for github doc and [https://github.com/curvenote/editor/blob/HEAD/demo/index.tsx](https://github.com/curvenote/editor/blob/HEAD/demo/index.tsx) in npmjs doc. The result is `page not found`. I think it should be something like: [https://github.com/curvenote/editor/tree/main/packages/editor/demo](https://github.com/curvenote/editor/tree/main/packages/editor/demo)

**Comment by rowanc1** [comment]
Thanks! This has been cleaned up, and will get it out to NPM soon. 🚀
