### ISSUE TITLE
Customize Figure/Equation references

### ISSUE THREAD

**Issue by rowanc1** [curvenote/editor#90]
When I reference an internal equation/figure/section the first letter of the resulting text is always capitalized (e.g. Section, Figure, Equation). Is there a way to make the text appear in lower case, or for the linked reference to appear in text as a different user defined string (eg Figure X would appear as Fig. X)?

**Comment by rowanc1** [comment]
Also here #117.

**Comment by stevejpurves** [comment]
Also section (header) references fit into the category
